Полетела студия, надеюсь всё работает...аминь!)
DecardCain21/PlaylistMaker2 pull request #1
Opened 2022-11-01 21:23 UTC by DecardCain21

Версия main.xml через constraint,не уверен как правильнее

2022-11-02 15:43 UTC, MagicUnderHood requested changes

2022-11-02 15:43 UTC, MagicUnderHood commented on app/src/main/res/drawable/button_big.xml
> +<?xml version="1.0" encoding="utf-8"?>
У тебя случайно дважды повторена строчка, один раз лишний. Из-за этого может возникать ошибка в студии. Если уберешь и запустишь Invalidate Caches and Restart, может помочь

2022-11-02 15:43 UTC, MagicUnderHood commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="328dp"
Если задавать фиксированную ширину, на маленьком экране кнопки буду занимать всё место, игнорируя отступы. Можно проверить на маленьком эмуляторе, например, Nexus S, с разрешением 480х800, вот как будет выглядеть:  
![image](https://user-images.githubusercontent.com/26437508/199532008-2286bf21-7557-4de6-bb16-85b3f6d51bdd.png)

Чтобы соответствовало дизайну независимо от устройства, задай ширину match_parent, а высоту можно ставить 0dp, поскольку она будет выставляться в зависимости от веса weight  
Дизайн главного экрана с использованием ConstraintLayout выглядит лучше, но для такого достаточно простого экрана лучше обойтись пока простыми LinearLayout и Button

2022-11-04 08:46 UTC, DecardCain21 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="328dp"
Увидел, спасибо большое...да у меня эмулятор не работает ни один :D

2022-11-05 23:24 UTC, MagicUnderHood commented on app/src/main/res/drawable-v24/ic_group.xml
> +      android:fillColor="#AEAFB4"/>
Можно использовать цвета из ресурсов

2022-11-05 23:24 UTC, MagicUnderHood commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/button_bigOne"
Лучше id задавать понятные, например, button_search

2022-11-05 23:24 UTC, MagicUnderHood commented on app/src/main/res/layout/activity_mainconstraint.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
В целом для достаточно простого экрана твой дизайн с LinearLayout подходит больше

2022-11-05 23:24 UTC, MagicUnderHood commented on app/src/main/res/layout/activity_settings.xml
> +            android:layout_height="61dp"
Можно тоже вынести в ресурсы

2022-12-13 18:27 UTC, closed without merging